# Generated by Django 4.2.13 on 2024-07-03 14:42

from django.db import migrations, models
import django.db.models.deletion
import sign.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='姓名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('face_emb', models.TextField(blank=True, verbose_name='人脸特征')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=sign.models.upload_to_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.user')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(verbose_name='上班时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='下班时间')),
                ('late_or_early', models.CharField(choices=[('late', '迟到'), ('early', '早退'), ('on_time', '准时')], default='on_time', max_length=10)),
                ('punching_location', models.TextField(verbose_name='打卡位置')),
                ('working_hours', models.DurationField(editable=False, verbose_name='工作时长')),
                ('photo_path', models.CharField(max_length=255, verbose_name='打卡照片保存路径')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='sign.user')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
            },
        ),
    ]
