# Generated by Django 4.2.13 on 2024-07-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='working_time'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='late_or_early',
            field=models.CharField(choices=[('late', 'late'), ('early', 'early'), ('on_time', 'on_time')], default='on_time', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='working_hours',
            field=models.DurationField(blank=True, editable=False, verbose_name='working_hours'),
        ),
    ]
