# Generated by Django 4.2.13 on 2024-07-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_alter_attendancerecord_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='08:00:00', verbose_name='Start Time')),
                ('middle_time', models.TimeField(default='12:00:00', verbose_name='Middle Time')),
                ('end_time', models.TimeField(default='18:00:00', verbose_name='End Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Work Time Setting',
                'verbose_name_plural': 'Work Time Settings',
            },
        ),
    ]
